### PR TITLE
Resolve #5: array_slice($argv, 1) is empty.

### LINKED ISSUE #5: What if $argv is empty?
Thank you for your replying at twitter @chitoku-k

### PR DESCRIPTION
**Pull request by m3m0r7**
吃驚

### CODE REVIEW

**Comment by chitoku-k** [comment]
I think you can simply verify whether `$words` is empty or not.

**Comment by m3m0r7** [comment]
@chitoku-k I fixed it

**Comment by chitoku-k** [comment]
The message isn't very good too. `The application has crashed.` should be suitable.

**Comment by hexium310** [comment]
"unnecessary"

**Comment by hexium310** [comment]
#5

**Comment by m3m0r7** [comment]
Okay.

**Pull request merged**
