### PR TITLE
Fix serious bug

### PR DESCRIPTION
**Pull request by mpyw**
This is so vulnerable

### CODE REVIEW

**Review by mpyw — COMMENTED** [review]
This may have breaking changes

**Comment by kb10uy** [comment]
:boom: :bomb: :boom:

**Comment by hexium310** [comment]
🥇

**Comment by chitoku-k** [comment]
Why did we overlook such a prominent bug?

**Comment by m3m0r7** [comment]
Because we are a cat.

**Comment by chitoku-k** [comment]
@memory-agape Hey, we cannot be a single cat. We should be cats!

**Comment by m3m0r7** [comment]
@chitoku-k just as you said

**Comment by mpyw** [comment]
@memory-agape You might need English lessons

**Comment by m3m0r7** [comment]
@mpyw HAI.

**Pull request merged**
